- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:

    - name: install firefox
      apt:
        name: firefox
        update_cache: yes

    - name: install default-jdk
      apt:
        name: default-jdk
        update_cache: yes

    - name: download geckodriver
      shell: wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz

    - name: unzip geckodriver
      shell: tar -xvzf geckodriver*

    - name: moving geckodriver to bin
      shell: mv geckodriver /usr/local/bin/

    - name: adding permission geckodriver
      shell: chmod +x geckodriver
      args:
        chdir: /usr/local/bin

    - name: export geckodriver path
      shell: export PATH=$PATH:/usr/local/bin/geckodriver

    - name: copy generator project
      copy:
        src: cadprev-generator/
        dest: ~/cadprev-generator

    - name: permission gradlew
      shell: chmod +x ~/cadprev-generator/gradlew

    #- name: run project
    #  shell: ./gradlew bootRun
    #  args:
    #    chdir: ~/cadprev-generator
  